### ISSUE TITLE
Export JSONObject with stapler throw NotExportableException exception when there is a field with null value.

### ISSUE THREAD

**Issue by aHenryJard** [stapler/stapler#172]
Using JSONObject in classes with annotation `@ExportedBean` works fine except when there is a field with null value.

Having a field with null value is correct in JSON format. So JSONObject with JSONNull should be exportable as other JSONObject.

The exception raised is:
```
org.kohsuke.stapler.export.NotExportableException: class net.sf.json.JSONNull doesn't have @ExportedBean

	at org.kohsuke.stapler.export.Property.writeValue(Property.java:298)
	at org.kohsuke.stapler.export.Property.writeValue(Property.java:168)
	at org.kohsuke.stapler.export.Property.writeValue(Property.java:266)
	at org.kohsuke.stapler.export.Property.writeValue(Property.java:168)
	at org.kohsuke.stapler.export.Property.writeTo(Property.java:153)
	at org.kohsuke.stapler.export.Model.writeNestedObjectTo(Model.java:223)
	at org.kohsuke.stapler.export.Model.writeTo(Model.java:194)
	at org.kohsuke.stapler.export.Model.writeTo(Model.java:214)
	at org.kohsuke.stapler.export.Model.writeTo(Model.java:182)
```

**Comment by batmat** [comment]
Done with https://github.com/stapler/stapler/pull/173 I assume?

**Comment by timja** [comment]
There's a test case added now that reproduces the issue @batmat 

It's ignored as the issue wasn't fixed:
https://github.com/stapler/stapler/blob/master/core/src/test/java/org/kohsuke/stapler/export/JSONDataWriterTest.java#L105
